version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"  # สำหรับ Jenkins Agent
    volumes:
      - jenkins_home:/var/jenkins_home
    # environment:
    #   - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
volumes:
  jenkins_home:
